# 应用名称
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://10.211.55.1:3306/ssm?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  type-aliases-package: com.itheima.pojo
  configuration:
    map-underscore-to-camel-case: true