# 应用名称
server:
  port: 80
Spring:
  redis:
    host: 10.211.55.9
    port: 6379
    password: 123456
    lettuce:
      pool:
        # 最大连接
        max-active: 8
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
        # 最大等待时间
        max-wait: 100ms


